// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3eEvmqVfuJw4HCtRi-oXWGMtG5LDOkQ',
    appId: '1:490155370469:web:3ec9c9453ed6c73ab3b10c',
    messagingSenderId: '490155370469',
    projectId: 'project-sync-8abca',
    authDomain: 'project-sync-8abca.firebaseapp.com',
    storageBucket: 'project-sync-8abca.firebasestorage.app',
    measurementId: 'G-0RP9NZ2VX9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3iD7W-Gu8ywg9Xx5MulEl0uCkl3y_tg',
    appId: '1:490155370469:ios:e87c201f810cb322b3b10c',
    messagingSenderId: '490155370469',
    projectId: 'project-sync-8abca',
    storageBucket: 'project-sync-8abca.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG3iD7W-Gu8ywg9Xx5MulEl0uCkl3y_tg',
    appId: '1:490155370469:ios:e87c201f810cb322b3b10c',
    messagingSenderId: '490155370469',
    projectId: 'project-sync-8abca',
    storageBucket: 'project-sync-8abca.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW3eEvmqVfuJw4HCtRi-oXWGMtG5LDOkQ',
    appId: '1:490155370469:web:e11435004dc7389db3b10c',
    messagingSenderId: '490155370469',
    projectId: 'project-sync-8abca',
    authDomain: 'project-sync-8abca.firebaseapp.com',
    storageBucket: 'project-sync-8abca.firebasestorage.app',
    measurementId: 'G-HJ4SRNSX3T',
  );
}
